/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ASerialPort */

#ifndef _Included_com_iamverylovely_ASerialPort
#define _Included_com_iamverylovely_ASerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ASerialPort
 * Method:    send
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_iamverylovely_ASerialPort_send
        (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     ASerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iamverylovely_ASerialPort_close
        (JNIEnv *, jobject);

/*
 * Class:     ASerialPort
 * Method:    reading
 * Signature: (IILjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_iamverylovely_ASerialPort_reading
        (JNIEnv *, jobject, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
